-- ════════════════════════════════════════════════════════════════════════════
-- E2M — material catalog seed. GENERATED from app/catalog.py; do not edit by hand.
--   python -m scripts.generate_seed_sql
-- Safe to re-run: existing materials are updated in place (ids are fixed).
-- Rates are indicative starting values (₹ per m² or running metre); verify before relying on them.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.materials (id, sor_code, rate_source, name, category, description, unit, material_rate, labor_rate, wastage_factor, coverage, unit_size, applies_to, colorable, swatch, suitability, maintenance, durability, render_prompt, is_active) values
  ('a38a68c6-2edb-51eb-a633-13218ac1e39b', '13.46.1', 'CPWD DSR-based (indicative)', 'Acrylic exterior emulsion paint', 'paint', 'Smooth acrylic exterior paint, two coats over one coat of exterior primer.', 'sqm', 95.0, 65.0, 0.05, '{"litres_per_sqm": 0.167, "coats": 2, "pack_litres": 20, "primer": true}'::jsonb, null, array['wall', 'parapet', 'pillar', 'balcony']::text[], true, '#f2e8d5', 'Most plastered walls; the standard choice for a fresh, even finish.', 'Wash with water every 1–2 years; repaint every 5–7 years.', 'Good resistance to rain and fading in moderate climates.', 'smooth matte exterior emulsion paint', true),
  ('e90f6b5e-e910-5c6b-a021-aed2c23e3d2e', null, 'Indicative market rate', 'Premium weatherproof emulsion (silicone/elastomeric)', 'paint', 'High-performance exterior paint with silicone additives that repels water and resists hairline cracks.', 'sqm', 140.0, 80.0, 0.05, '{"litres_per_sqm": 0.143, "coats": 2, "pack_litres": 20, "primer": true}'::jsonb, null, array['wall', 'parapet', 'pillar', 'balcony']::text[], true, '#e9e4da', 'Walls facing heavy rain or coastal humidity; homes with recurring damp patches.', 'Dirt-resistant; wash every 2–3 years; repaint every 8–10 years.', 'Excellent water and UV resistance; bridges hairline cracks.', 'premium weatherproof exterior paint, slight sheen', true),
  ('c810d8d4-6918-524e-9065-e4f4efd871aa', '13.45.1', 'CPWD DSR-based (indicative)', 'Textured exterior paint', 'texture', 'Thick textured coating (sand/roller finish) over exterior primer.', 'sqm', 150.0, 75.0, 0.05, '{"litres_per_sqm": 0.328, "coats": 2, "pack_litres": 25, "primer": true}'::jsonb, null, array['wall', 'parapet', 'pillar', 'balcony']::text[], true, '#d9c7a8', 'Feature walls and pillars; hides minor plaster unevenness.', 'Textures hold dust; wash yearly; recoat every 7–10 years.', 'Very durable and crack-hiding; harder to touch up invisibly.', 'sand-textured exterior wall coating', true),
  ('f6939ee6-cf31-54b2-8206-85fac58e7483', null, 'Indicative market rate', 'Waterproof cement paint (economy)', 'paint', 'Cement-based powder paint mixed with water, two coats.', 'sqm', 30.0, 25.0, 0.05, '{"kg_per_sqm": 0.33, "coats": 2, "pack_kg": 25}'::jsonb, null, array['wall', 'parapet', 'pillar', 'balcony']::text[], true, '#ece6dc', 'Budget refresh of compound walls, parapets and service areas.', 'Chalks and fades faster; repaint every 3–4 years.', 'Basic weather protection; colours are limited and fade sooner.', 'flat cement paint finish', true),
  ('cd1b28b9-51a4-5bb4-9dc1-7b304c959a99', '13.1', 'CPWD DSR-based (indicative)', 'Cement plaster 12 mm (1:4) — replastering', 'plaster', 'New 12 mm cement-sand plaster where the old plaster is cracked or hollow.', 'sqm', 160.0, 135.0, 0.05, '{"thickness_mm": 12, "mix": "1:4"}'::jsonb, null, array['wall', 'parapet', 'pillar', 'balcony']::text[], false, '#c9c3b8', 'Damaged or uneven walls before painting or texturing.', 'Must be painted or coated; cure for 7 days before painting.', 'Long-lasting base layer when properly cured.', 'fresh grey cement plaster', true),
  ('de20beea-c23c-50bc-b42a-f5710559150e', null, 'Indicative market rate', 'Sandstone cladding (20–25 mm)', 'stone_cladding', 'Natural sandstone slabs fixed with adhesive and anchors, with grouted joints.', 'sqm', 1300.0, 450.0, 0.1, null, '{"tile_w_m": 0.6, "tile_h_m": 0.3}'::jsonb, array['wall', 'parapet', 'pillar', 'balcony']::text[], false, '#c8a97e', 'Feature walls, entrance pillars and boundary walls for a warm natural look.', 'Seal every 2–3 years to limit staining and moss.', 'Very durable; porous, so sealing matters in rainy areas.', 'natural sandstone cladding, stacked rectangular slabs', true),
  ('0f40b2b2-acdd-5ba9-9f83-feadf6a6c872', null, 'Indicative market rate', 'Granite cladding (20 mm)', 'stone_cladding', 'Polished or flamed granite slabs with mechanical fixing and grooved joints.', 'sqm', 2400.0, 600.0, 0.1, null, '{"tile_w_m": 0.6, "tile_h_m": 0.6}'::jsonb, array['wall', 'parapet', 'pillar', 'balcony']::text[], false, '#5f5b57', 'Ground-floor walls, pillars and entrances that take knocks and splashes.', 'Almost none; occasional washing.', 'Excellent; resists water, stains and abrasion for decades.', 'dark granite stone cladding panels', true),
  ('0100ed47-4222-5c3c-bf97-14bf08916cf5', null, 'Indicative market rate', 'Ceramic elevation wall tiles (300 × 450 mm)', 'tiles', 'Exterior-grade ceramic tiles fixed with polymer tile adhesive.', 'sqm', 650.0, 300.0, 0.08, null, '{"tile_w_m": 0.45, "tile_h_m": 0.3}'::jsonb, array['wall', 'parapet', 'pillar', 'balcony']::text[], false, '#b9a48f', 'Budget-friendly patterned or brick-look elevations.', 'Wash yearly; check joints and re-grout if water seeps in.', 'Good; individual tiles can loosen on poorly prepared walls.', 'brick-look ceramic elevation tiles', true),
  ('18b9fd34-a847-5673-9ec6-32366d12630a', null, 'Indicative market rate', 'Vitrified / porcelain elevation tiles (300 × 600 mm)', 'tiles', 'Low-porosity vitrified tiles in stone or wood looks, fixed with adhesive.', 'sqm', 950.0, 350.0, 0.08, null, '{"tile_w_m": 0.6, "tile_h_m": 0.3}'::jsonb, array['wall', 'parapet', 'pillar', 'balcony']::text[], false, '#9a8f86', 'Modern elevations wanting a stone or wood look at lower cost than stone.', 'Very low; occasional washing.', 'Excellent stain and water resistance.', 'large-format porcelain stone-look facade tiles', true),
  ('522fe85b-f710-588e-935b-218da74e7c09', null, 'Indicative market rate', 'ACP cladding (4 mm aluminium composite)', 'panels', 'Aluminium composite panels on an aluminium frame with sealed joints.', 'sqm', 1300.0, 450.0, 0.1, null, '{"panel_w_m": 1.22, "panel_h_m": 2.44}'::jsonb, array['wall', 'parapet', 'pillar', 'balcony']::text[], true, '#8c9399', 'Modern, flat, single-colour facades and feature bands.', 'Wash every 1–2 years; check joint sealant.', 'Good; choose fire-retardant (FR) grade panels.', 'smooth metallic aluminium composite panels with fine joints', true),
  ('3a34712e-89dc-5b76-ba96-1991e24be727', null, 'Indicative market rate', 'HPL exterior panels (wood look, 8 mm)', 'panels', 'High-pressure laminate panels with a wood finish on a ventilated frame.', 'sqm', 2800.0, 600.0, 0.1, null, '{"panel_w_m": 1.3, "panel_h_m": 3.05}'::jsonb, array['wall', 'parapet', 'pillar', 'balcony']::text[], false, '#8a5a3b', 'Warm wood-look features without the upkeep of real timber.', 'Very low; wash yearly.', 'UV- and weather-resistant for 10+ years.', 'wood-grain exterior laminate cladding boards', true),
  ('b781d49f-a2bf-5dde-87b2-5a0bacec30bd', null, 'Indicative market rate', 'MS railing, painted (900 mm high)', 'railing', 'Mild-steel railing with primer and two coats of enamel paint.', 'rmt', 1600.0, 500.0, 0.05, null, null, array['railing']::text[], true, '#2b2b2b', 'Balconies and terraces on a budget; any colour.', 'Repaint every 2–3 years to prevent rust.', 'Strong; rusts if the paint is not maintained.', 'black painted mild steel balcony railing', true),
  ('85c5f72c-4534-54dd-be29-e02e7ec102e7', null, 'Indicative market rate', 'Stainless steel railing (SS 304, 900 mm high)', 'railing', 'Grade 304 stainless steel posts and rails with a brushed finish.', 'rmt', 3200.0, 700.0, 0.05, null, null, array['railing']::text[], false, '#c0c4c8', 'Modern balconies and stairs; low upkeep.', 'Wipe occasionally; no painting.', 'Excellent corrosion resistance (use SS 316 near the sea).', 'brushed stainless steel balcony railing', true),
  ('cabbac2d-e00b-5df2-8245-e3d82c3e849a', null, 'Indicative market rate', 'Toughened glass railing (12 mm, SS fittings)', 'railing', '12 mm toughened glass panels with stainless steel spigots and handrail.', 'rmt', 6500.0, 1200.0, 0.05, null, null, array['railing']::text[], false, '#bcd7e0', 'Open views and a contemporary look on balconies and terraces.', 'Clean glass monthly in dusty areas.', 'Very durable; use toughened (or laminated) safety glass only.', 'frameless clear toughened glass balcony railing', true)
on conflict (id) do update set
  sor_code = excluded.sor_code,
  rate_source = excluded.rate_source,
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  unit = excluded.unit,
  material_rate = excluded.material_rate,
  labor_rate = excluded.labor_rate,
  wastage_factor = excluded.wastage_factor,
  coverage = excluded.coverage,
  unit_size = excluded.unit_size,
  applies_to = excluded.applies_to,
  colorable = excluded.colorable,
  swatch = excluded.swatch,
  suitability = excluded.suitability,
  maintenance = excluded.maintenance,
  durability = excluded.durability,
  render_prompt = excluded.render_prompt,
  is_active = excluded.is_active;
